IMAGE   bgtile    "tiles/bgtile.png"  0
IMAGE   tile1    "tiles/tile1.png"  0
IMAGE floor "tiles/floor.bmp" 0
IMAGE wall "tiles/wall.bmp" 0
IMAGE light "tiles/light.bmp" 0
IMAGE eye "tiles/eye.png" 0
IMAGE finestra "tiles/finestra.bmp" 0
BITMAP  palme "tiles/palme.bmp" 0
BITMAP moon "tiles/moon.png" 0